using './main.bicep'

// Short prefix for resource names — must be unique within your Azure subscription.
// Resources created: <name>-foundry (Azure Foundry account)
param name = 'tripbot'

// Name for the Foundry project visible in ai.azure.com
param projectName = 'tripbot-project'

// Model to deploy. gpt-4o-mini is recommended: low cost, fast, sufficient for all modules.
param modelDeploymentName = 'gpt-4o-mini'

// Capacity in thousands of tokens per minute. 10 = 10K TPM (sufficient for learning).
param modelCapacity = 10

// Your Azure user object ID — grants passwordless access via DefaultAzureCredential.
// DO NOT edit this file to add your principalId — pass it inline on the CLI instead:
//   --parameters principalId=$(az ad signed-in-user show --query id -o tsv)
// This keeps your personal ID out of source control.
param principalId = ''
